### ISSUE TITLE
Sliding window perplexity with truncated documents

### ISSUE THREAD

**Issue by totolacky** [jquesnelle/yarn#13]
Hi! Thanks for sharing your nice work.
I have some questions about the perplexity evaluation setup.

In Figure 1, it is mentioned that the sliding window perplexity is reported, with documents truncated to the evaluation context length.
I was wondering if that makes sense, because (as far as I understood) sliding window evaluation is something that you do when the document length is longer than the evaluation context length.

Also, is there a particular reason you used truncation for proof-pile and not for gov_report?

Thanks in advance!

**Comment by bloc97** [comment]
Sliding window evaluation was used in order to give as much chance as possible for lower context models (eg. 32k and 100k), because we're summing across the lowest PPL point for all models.

Proof-pile data was truncated so we can compare PPL across different lengths of the data, independently of the actual context size of models.

**Comment by totolacky** [comment]
I understood that sliding window evaluation enables a fair comparison.

However, I was wondering if sliding window evaluation makes any difference when the data is truncated.
In those cases, the evaluation length equals the data length, so the window never 'slides'.

**Comment by jquesnelle** [comment]
You are right -- it doesn't make a difference comparatively (I wondered if anyone would notice this 😂), but it was still evaluated with that method, meaning that if truncated to 8K, we first evaluated [0, 8k], then [0 + 256, 8k - 256] etc.

We needed to put it in the paper for reproducibility reasons.

> Also, is there a particular reason you used truncation for proof-pile and not for gov_report

This is the heart of the matter; we wanted to show the behavior of PPL as we simulated the "maximum" context size of the model (via truncation). This allows there to be an X axis in Figure 1.

To put it bluntly, we did it this way for Proof-pile to create the pretty picture. The gov_report results represent a full context-window agnostic PPL. It's of note that the behavior of both the "true" sliding window PPL and the truncated one seem to follow the same divergence between models, meaning that either are representative (although we did not know it would be this way at first)

**Comment by PeiqinSun** [comment]
I also found it. In truncate setting, evaluation data length == evaluation-context-window-size, the sliding window also be set as data-length, which means that window is never `slides`. But in you paper, fig1 show sliding-window=256 in truncate setting, is it wrong?

**Comment by smartparrot** [comment]
> I also found it. In truncate setting, evaluation data length == evaluation-context-window-size, the sliding window also be set as data-length, which means that window is never `slides`. But in you paper, fig1 show sliding-window=256 in truncate setting, is it wrong?

I have the same finding when I do experiment for mixtral7b, why?
