### ISSUE TITLE
Confirmation of License

### ISSUE THREAD

**Issue by RonanKMcGovern** [jquesnelle/yarn#14]
Nice work making this.

Could you clarify/confirm the license here? I see MIT License here on Github and no license on HuggingFace.

I would have assumed this has to at least be Meta Community License as that would transfer through because of using Llama 2.

It looks like the only new training data added is [PG-19](https://github.com/deepmind/pg19), which seems to be Apache 2- so it seems that YaRN could take on a Meta Community License.

**Comment by bloc97** [comment]
Yeah, MIT license for all of the code.
Models and Dataset are bound by their respective licenses.

**Comment by RonanKMcGovern** [comment]
thanks! appreciate it
