### ISSUE TITLE
Please, writting LISENSE

### ISSUE THREAD

**Issue by chatblanc-ciel** [jquesnelle/yarn#20]
Hello, I am interested in using your models.

What's LISENSE [these models](https://github.com/jquesnelle/yarn#models)？
I want to know that.

**Comment by Cebtenzzre** [comment]
Already answered in #14. I believe the Meta Community License applies.

**Comment by chatblanc-ciel** [comment]
@Cebtenzzre
Thank you very much!
I missed it.
