### ISSUE TITLE
Compute Requirements

### ISSUE THREAD

**Issue by torphix** [jquesnelle/yarn#9]
Great stuff!

Just out of curiosity what was the compute setup used?
I couldn't seem to find details such as GPU type and cluster size used in the paper

Thanks!

**Comment by jquesnelle** [comment]
The models were all trained on 8x 8 A100 80 GB nodes (so 64 total GPUs). However, we also (redundantly) trained the 7B models on a single 8x A100 80 GB node. This took about 3 days on the single 8x node. The 13B requires at least 2 8x nodes.

For inference, all evaluations were run on either an 8x A40 48 GB node or an 8x A100 80 GB node. We found that that 7B 64k context can take as "little" as 160 GB of VRAM in bfloat16, through around 360 GB of VRAM for 13B at 128k context.

**Comment by goog** [comment]
how many 3090 does it need to train 7b Lora ?

**Comment by kyleliang919** [comment]
I am hitting OOM on mistral with the 8K dataset on 2 80GB H100s while finetuning. I wonder if anything special needs to be done here.
